# -*- coding: utf-8 -*-
"""cancerprediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dTFxE9y-p67XYUNuRrtfy2p3FhLiC1xt
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import confusion_matrix , ConfusionMatrixDisplay

#load datasets

data = load_breast_cancer(as_frame=True)
x= data.data
y=data.target

print("Numbert of sanmples", x.shape[0])
print("Number of features", x.shape[1])

print("\nClass distribution")
print(y.value_counts())

X_train, X_test, y_train, y_test = train_test_split(x,y,test_size= 0.2, random_state=42)

X_train.head()

#standardise the data

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

X_train

#train model
model = LogisticRegression()
model.fit(X_train, y_train)

#predict the data
y_pred = model.predict(X_test)

#Evaluation metrics
print("Accuracy_score : ", accuracy_score(y_test,y_pred))
print("Pression Score : ", precision_score(y_test, y_pred))
print("Recall score : ",recall_score(y_test,y_pred))
print("F1 score : ",f1_score(y_test, y_pred))

#confussion matrix
cm = confusion_matrix(y_test,y_pred)
print("\n Confussion Matrix")
cm

#plot confussion matrix
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot(cmap="Blues")
plt.title("Confussion Matrix")
plt.show()